# Site settings
site: RezNetDevOps
title: RezNetDevOps - NetDevOps by Reza
keywords: RezNetDevOps, blog
description: >-
  RezNetDevOps - NetDevOps by Reza
lang: en-US
timezone:  Europe/Istanbul
#repo: https://github.com/onepase/Ephesus # site repo [optional]
#google_verify:      XXX # Put your Google Verification here
google_analytics:   G-MSR5EXNS6E # Put your Google Analytics code
discus-identifier:  Reza

# Author settings
author:
  name: Netdevops by Reza
  bio: Network Engineer <br> Microsoft sys/cloud admin <br> NetDevOps tools Engineer <br> CCNP Enterprise <br> MCSE Infra <br> MCSE Productivity
  picture: assets/images/profile.jpg 
  github: reznetdevops # github username
  twitter: reznetdevops # twitter username
  #facebook: onepase # facebook username
  instagram: reznetdevops # instagram username
  #youtube: https://www.youtube.com/channel/UCMmAto-wxBootXN91AzBiDg # youtube username
  linkedin: reznetdevops # linkedin username
  email: reznetdevops@gmail.com # email adress


# URL settings
url: "https://reznetdevops.github.io" # Domain Name of host. [username].github.io for github pages
baseurl: "" # sub folder for jekyll site. only if jekyll site not in root of host. leave blank if not wishd. always add / in front.
permalink: pretty

markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge


exclude:
  - .jekyll-cache
  - .obsidian
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md
  - CONTRIBUTING.md

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-relative-links
paginate: 20
paginate_path: "/page/:num"

collections:
  pages:
    output: true
    permalink: /:name
  posts:
    output: true
    permalink: /:slug
  
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

relative_links:
  enabled:     true
  collections: false
theme: jekyll-theme-dinky